In [1]:
from Fundamentals import Bayesian_Optimization
import numpy as np
import pymc as pm

In [2]:
def gaussian_model(lam, n_samples):
    
    gaussian_model = pm.Model()
        
    with gaussian_model:

        theta = pm.Normal("theta", mu=lam["mu_1"], sigma=lam["sigma_1"])
            
        Y_obs = pm.Normal("Y_obs", mu=theta, sigma=lam["sigma"], observed=1.)
        
    with gaussian_model:
        
        idata = pm.sample_prior_predictive(samples = n_samples)
        
    return idata


partitions = np.array([[-1000, -5], [-5, -1], [-1, 3], [3, 1000]])

expert_probs = [np.array([0.1, 0.2, 0.6, 0.1])]



BO = Bayesian_Optimization(pymc_sampling_func=gaussian_model,
                              J = 1,
                              alpha=None,
                              target_type="continuous",
                              target_samples=1000)


   

param_names = ["mu_1", "sigma_1", "sigma", "alpha"]
param_bounds = [[-10., 10.], [0.00001, 4.], [0.00001, 4.], [0.1, 20.]]
param_expected_vals = [-1, 3, 0.5, None]
param_weights = [1, 1, 1]

   
    
best_params = BO.optimize_hyperparams(param_names=param_names,
                                      param_bounds=param_bounds,
                                      param_expected_vals = param_expected_vals,
                                      param_weights = param_weights,
                                      partitions=partitions,
                                      expert_probs=expert_probs,
                                      n_trials=75)  


[INFO 06-15 12:25:16] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter mu_1. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 06-15 12:25:16] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter sigma_1. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 06-15 12:25:16] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter sigma. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 06-15 12:25:16] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter alpha. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter d

In [3]:
best_params

{'mu_1': -0.6267276708243035,
 'sigma_1': 3.456495458200379,
 'sigma': 0.4645866276015849,
 'alpha': 11.513152262972097}

In [4]:
BO.eval_function(best_params, partitions, expert_probs)

Sampling: [Y_obs, theta]


Array(15.47217, dtype=float32)

In [5]:
BO.get_model_probs(best_params, partitions)

Sampling: [Y_obs, theta]


[array([0.101, 0.351, 0.386, 0.162])]

In [6]:
def classification_model(lam, n_samples):
    
    RANDOM_SEED = 8927
    
    covs = np.array([[1.3, 0.7, 0.5, -0.7, -0.5],
                     [1, 0.5, 0.4, -0.8, 0],
                     [0.3, 0.7, 2, -2, 0.2]])
    
    classification_model = pm.Model()

    with classification_model:

        theta_1 = pm.Normal("theta_1", mu=lam["mu_1"], sigma=lam["sigma_1"])
        theta_2 = pm.Normal("theta_2", mu=lam["mu_2"], sigma=lam["sigma_2"])
        theta_3 = pm.Normal("theta_3", mu=lam["mu_3"], sigma=lam["sigma_3"])
        theta_4 = pm.Normal("theta_4", mu=lam["mu_4"], sigma=lam["sigma_4"])
        theta_5 = pm.Normal("theta_5", mu=lam["mu_5"], sigma=lam["sigma_5"])
        
        theta = pm.math.stack([theta_1, theta_2, theta_3, theta_4, theta_5])
        
        p = pm.math.dot(covs, theta)

        p = 0.5 + 0.5 * pm.math.erf(p / pm.math.sqrt(2))
                    
        Y_obs = pm.Bernoulli("Y_obs", p = p, observed=np.ones(covs.shape[0]))
        
    with classification_model:
        idata = pm.sample_prior_predictive(random_seed=RANDOM_SEED, samples = n_samples)
        
    return idata



BO = Bayesian_Optimization(pymc_sampling_func=classification_model,
                              J = 3,
                              alpha=None,
                              target_type="discrete",
                              target_samples=1000)
   

param_names = ["mu_1", "sigma_1",
               "mu_2", "sigma_2",
               "mu_3", "sigma_3",
               "mu_4", "sigma_4",
               "mu_5", "sigma_5",
               "alpha"]

partitions = np.array([0, 1])

expert_probs = [np.array([0.65, 0.35]),
                np.array([0.3, 0.7]),
                np.array([0.2, 0.8])]



param_bounds = [[-6., 6.], [0.00001, 2.],
                [-6., 6.], [0.00001, 2.],
                [-6., 6.], [0.00001, 2.],
                [-6., 6.], [0.00001, 2.],
                [-6., 6.], [0.00001, 2.],
                [0.1, 200.]]

param_expected_vals = [1, 1,
                       -0.2, 1,
                       -1, 1,
                       1, 1,
                       -0.5, 1,
                       None]



param_weights = [1, 0.5,
                 1, 0.5,
                 1, 0.5,
                 1, 0.5,
                 1, 0.5]
   
    
best_params = BO.optimize_hyperparams(param_names=param_names,
                                      param_bounds=param_bounds,
                                      param_expected_vals = param_expected_vals,
                                      param_weights = param_weights,
                                      partitions=partitions,
                                      expert_probs=expert_probs,
                                      n_trials=100)  



[INFO 06-15 12:27:05] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter mu_1. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 06-15 12:27:05] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter sigma_1. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 06-15 12:27:05] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter mu_2. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 06-15 12:27:05] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter sigma_2. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter 

In [7]:
best_params

{'mu_1': 0.7997459918675123,
 'sigma_1': 0.8153397513191514,
 'mu_2': -4.777905773812542,
 'sigma_2': 0.5714246566915949,
 'mu_3': 1.4153790177752388,
 'sigma_3': 1.1903706650615598,
 'mu_4': -1.6325108545831153,
 'sigma_4': 0.9640131901977391,
 'mu_5': 0.10992390324557011,
 'sigma_5': 1.3644795551305133,
 'alpha': 6.239994339239339}

In [8]:
BO.eval_function(best_params, partitions, expert_probs)

Sampling: [Y_obs, theta_1, theta_2, theta_3, theta_4, theta_5]


Array(29.274467, dtype=float32)

In [9]:
BO.get_model_probs(best_params, partitions)

Sampling: [Y_obs, theta_1, theta_2, theta_3, theta_4, theta_5]


[array([0.611, 0.389]), array([0.447, 0.553]), array([0.196, 0.804])]

In [10]:
partitions = np.array([0, 1])

expert_probs = [np.array([0.8854, 0.1146]),
                np.array([0.7857, 0.2143]),
                np.array([0.2237, 0.7763]),
                np.array([0.9023, 0.0977]),
                np.array([0.8167, 0.1833]),
                np.array([0.7857, 0.2143])]



def trauma_center_model(lam, n_samples):
    
    
    covs = np.array([[1,1,1,1,1,1],
                     [25,25,41,41,33,33],
                     [7.84, 3.34, 3.34, 7.84, 5.74, 5.74],
                     [60, 10, 60, 10, 35, 35],
                     [0,0,1,1,0,1],
                     [0,0,60,10,0,35]]).T
    
    trauma_center_model = pm.Model()

    with trauma_center_model:

        theta_1 = pm.Normal("theta_1", mu=lam["mu_1"], sigma=lam["sigma_1"])
        theta_2 = pm.Normal("theta_2", mu=lam["mu_2"], sigma=lam["sigma_2"])
        theta_3 = pm.Normal("theta_3", mu=lam["mu_3"], sigma=lam["sigma_3"])
        theta_4 = pm.Normal("theta_4", mu=lam["mu_4"], sigma=lam["sigma_4"])
        theta_5 = pm.Normal("theta_5", mu=lam["mu_5"], sigma=lam["sigma_5"])
        theta_6 = pm.Normal("theta_6", mu=lam["mu_6"], sigma=lam["sigma_6"])
        
        theta = pm.math.stack([theta_1, theta_2, theta_3, theta_4, theta_5, theta_6])
        
        xTtheta = pm.math.dot(covs, theta)
        
        p = pm.math.exp(xTtheta) / (1 + pm.math.exp(xTtheta))
        
        Y_obs = pm.Bernoulli("Y_obs", p = p, observed=np.ones(covs.shape[0]))
        
    with trauma_center_model:
        idata = pm.sample_prior_predictive(samples=n_samples)
        
    return idata



BO = Bayesian_Optimization(pymc_sampling_func=trauma_center_model,
                              J = 6,
                              alpha=None,
                              target_type="discrete",
                              target_samples=2000)
   

param_names = ["mu_1", "sigma_1",
               "mu_2", "sigma_2",
               "mu_3", "sigma_3",
               "mu_4", "sigma_4",
               "mu_5", "sigma_5",
               "mu_6", "sigma_6",
               "alpha"]


param_bounds = [[-3., 3.], [0.00001, 2.],
                [-3., 3.], [0.00001, 2.],
                [-3., 3.], [0.00001, 2.],
                [-3., 3.], [0.00001, 2.],
                [-3., 3.], [0.00001, 2.],
                [-3., 3.], [0.00001, 2.],
                [0.1, 100.]]


param_expected_vals = [-1.8, 1.1,
                       0.07, 0.02,
                       -0.6, 0.14,
                       0.05, 0.01,
                       -1.1, 1.06,
                       -0.02, 0.03,
                       None]

param_weights = np.ones(len(param_bounds))
   
   
   
best_params = BO.optimize_hyperparams(param_names=param_names,
                                      param_bounds=param_bounds,
                                      param_expected_vals = param_expected_vals,
                                      param_weights = param_weights,
                                      partitions=partitions,
                                      expert_probs=expert_probs,
                                      n_trials=100)  

[INFO 06-15 12:31:02] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter mu_1. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 06-15 12:31:02] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter sigma_1. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 06-15 12:31:02] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter mu_2. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 06-15 12:31:02] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter sigma_2. If that is not the expected value type, you can explicitly specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter 

In [11]:
best_params

{'mu_1': -2.2201843235357224,
 'sigma_1': 0.8436002642088464,
 'mu_2': -1.1109823683576043,
 'sigma_2': 1.4338714258554965,
 'mu_3': -0.6008300968599225,
 'sigma_3': 1.90099964829382,
 'mu_4': -0.8923124524340542,
 'sigma_4': 1.3919582523180267,
 'mu_5': -0.9458522818397563,
 'sigma_5': 0.8076373185129425,
 'mu_6': 1.319947274268185,
 'sigma_6': 2.0,
 'alpha': 9.737697906448805}

In [12]:
BO.get_model_probs(best_params, partitions)

Sampling: [Y_obs, theta_1, theta_2, theta_3, theta_4, theta_5, theta_6]


[array([0.828, 0.172]),
 array([0.8685, 0.1315]),
 array([0.5755, 0.4245]),
 array([0.793, 0.207]),
 array([0.862, 0.138]),
 array([0.6245, 0.3755])]

In [13]:
expert_probs

[array([0.8854, 0.1146]),
 array([0.7857, 0.2143]),
 array([0.2237, 0.7763]),
 array([0.9023, 0.0977]),
 array([0.8167, 0.1833]),
 array([0.7857, 0.2143])]

In [14]:
BO.eval_function(best_params, partitions, expert_probs)

Sampling: [Y_obs, theta_1, theta_2, theta_3, theta_4, theta_5, theta_6]


Array(6.654009, dtype=float32)